version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: opticash-iam-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruben123
    ports:
      - "5432:5432"
    networks:
      - opticash-net

  eureka-server:
    build: ./microservice-eureka
    container_name: microservice-eureka
    ports:
      - "8761:8761"
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  api-gateway:
    build: ./microservice-gateway
    container_name: microservice-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  msvc-iam:
    build: ./microservice-iam
    container_name: microservice-iam
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ruben123
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  msvc-bills:
    build: ./microservice-bills
    container_name: microservice-bills
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ruben123
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  msvc-households:
    build: ./microservice-households
    container_name: microservice-households
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ruben123
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  msvc-contributions:
    build: ./microservice-contributions
    container_name: microservice-contributions
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ruben123
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

  msvc-settings:
    build: ./microservice-settings
    container_name: microservice-settings
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ruben123
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - opticash-net

networks:
  opticash-net:
    driver: bridge
