server:
  port: 8080

spring:
  application:
    name: microservice-gateway

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "https://front-end-xxnb.vercel.app"
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      routes:

        # IAM public paths
        - id: iam-public
          uri: lb://microservice-iam
          predicates:
            - Path=/api/v1/authentication/**
          

        # IAM secure
        - id: iam-secure
          uri: lb://microservice-iam
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/roles/**
          filters:
            - JwtAuthenticationFilter

        # Bills
        - id: bills
          uri: lb://microservice-bills
          predicates:
            - Path=/api/v1/bills/**
          filters:
            - JwtAuthenticationFilter

        # Households
        - id: households
          uri: lb://microservice-households
          predicates:
            - Path=/api/v1/households/**
          filters:
            - JwtAuthenticationFilter

        # Household Members
        - id: household-members
          uri: lb://microservice-households
          predicates:
            - Path=/api/v1/household-members/**
          filters:
            - JwtAuthenticationFilter

        # Contributions
        - id: contributions
          uri: lb://microservice-contributions
          predicates:
            - Path=/api/v1/contributions/**
            - Path=/api/v1/member-contributions/**
          filters:
            - JwtAuthenticationFilter


jwt:
  secret: "mysupersecretkeythatshouldbeatleast32chars"
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.fiscalliance.gateway.filters: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true
